# Generated by Django 4.2 on 2023-10-05 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='menu_height',
            field=models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
